/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import {GLTFActions, useHandleAnimation} from "./useHandleAnimation";

type GLTFResult = GLTF & {
  nodes: {
    Cube004: THREE.SkinnedMesh
    Cube004_1: THREE.SkinnedMesh
    Cube004_2: THREE.SkinnedMesh
    Cube004_3: THREE.SkinnedMesh
    Cube004_4: THREE.SkinnedMesh
    Bone: THREE.Bone
  }
  materials: {
    Skin: THREE.MeshStandardMaterial
    Main: THREE.MeshStandardMaterial
    Details: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    Face: THREE.MeshStandardMaterial
  }
}



export default function Ninja({moving, ...props}: JSX.IntrinsicElements['group'] & {
    moving: boolean,
}) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/Ninja_Male.glb') as GLTFResult
  // @ts-ignore
    const { actions } = useAnimations(animations, group) as { actions: GLTFActions}

    useHandleAnimation(actions, moving)

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <skinnedMesh castShadow receiveShadow material={materials.Skin} geometry={nodes.Cube004.geometry} skeleton={nodes.Cube004.skeleton} />
      <skinnedMesh castShadow receiveShadow material={materials.Main} geometry={nodes.Cube004_1.geometry} skeleton={nodes.Cube004_1.skeleton} />
      <skinnedMesh castShadow receiveShadow
        material={materials.Details}
        geometry={nodes.Cube004_2.geometry}
        skeleton={nodes.Cube004_2.skeleton}
      />
      <skinnedMesh castShadow receiveShadow material={materials.Grey} geometry={nodes.Cube004_3.geometry} skeleton={nodes.Cube004_3.skeleton} />
      <skinnedMesh castShadow receiveShadow material={materials.Face} geometry={nodes.Cube004_4.geometry} skeleton={nodes.Cube004_4.skeleton} />
    </group>
  )
}

useGLTF.preload('/models/Ninja_Male.glb')
